[package]
name = "fl-www-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
once_cell = "1.9.0"

serde_json = "1.0.73"
serde = { version = "1.0.132", features = ["derive"] }

chrono = { version = "0.4.19", features = ["wasmbind", "serde"] }
parking_lot = { version = "0.11.2", features = ["wasm-bindgen"] }
typed-builder = "0.9.1"

pulldown-cmark = { version = "0.8.0", default-features = false }

hex = "0.4.3"
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8"
