[package]
name = "bounce-query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.19"
bounce = { git = "https://github.com/futursolo/bounce.git" }
yew = "0.19.3"
once_cell = "1.9.0"
async-trait = "0.1.52"
