[workspace]
members = [
    "packages/fl-www",
    "packages/fl-www-cli",
    "packages/fl-www-core",
    "packages/fl-www-macros",
    "packages/fl-www-common",
    "packages/fl-www-agents",
    "packages/fl-www-backend",
    "packages/yew-query",
    "packages/bounce-query",
]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1

[profile.release.package."*"]
codegen-units = 1
opt-level     = "z"
