[workspace]
members = [
    "packages/fl-www",
    "packages/fl-www-cli",
    "packages/fl-www-core",
    "packages/fl-www-macros",
    "packages/fl-www-common",
    "packages/fl-www-agents",
    "packages/yew-query",
]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true
