[workspace]
members = [
    "packages/fl-www",
    "packages/fl-www-old",
    "packages/fl-www-macros",
    "packages/fl-www-common",
    # "packages/fl-www-agents",
]

[profile.release]
opt-level = "z"
lto = true
