[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_CLIPPY_ARGS = "--all-features -- -D warnings"
FL_WWW_GITHUB_CLIENT_ID = "72f7c210f18ee7928a30"
FL_WWW_BACKEND_CONTENT_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"

# stctl
[tasks.stctl]
workspace = false
command = "cargo"
args = ["run", "--bin", "stctl", "--", "${@}"]

[tasks.start]
workspace = false
command = "cargo"
args = ["run", "--bin", "stctl", "--", "serve"]

[tasks.build]
workspace = false
command = "cargo"
args = ["run", "--bin", "stctl", "--", "build", "--release"]
