[tasks.run-local-backend]
workspace = false
command = "cargo"
args = ["run", "--bin", "fl-www-cli", "serve", "--addr=localhost:9740"]

[tasks.serve-local-frontend]
workspace = false
command = "trunk"
args = ["serve", "--open", "index.html"]

[tasks.serve-local-frontend.env]
FL_WWW_BACKEND_PREFIX = "http://localhost:9740/"
FL_WWW_GITHUB_CLIENT_ID = "72f7c210f18ee7928a30"

[tasks.build-local-frontend]
workspace = false
command = "trunk"
args = ["build", "--release", "index.html"]

[tasks.build-local-frontend.env]
FL_WWW_BACKEND_PREFIX = "http://localhost:9740/"
FL_WWW_GITHUB_CLIENT_ID = "72f7c210f18ee7928a30"
