# cargo build
[tasks.build-dev-worker-highlight]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown", "--bin", "fl-worker-highlight"]

[tasks.build-dev-worker-markdown]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown", "--bin", "fl-worker-markdown"]

# wasm-bindgen
[tasks.bindgen-dev-worker-highlight]
command = "wasm-bindgen"
args = ["--target", "no-modules", "--no-typescript", "--out-dir", "worker-dist/", "--out-name", "fl-worker-highlight", "target/wasm32-unknown-unknown/release/fl-worker-highlight.wasm"]
dependencies = ["build-dev-worker-highlight"]

[tasks.bindgen-dev-worker-markdown]
command = "wasm-bindgen"
args = ["--target", "no-modules", "--no-typescript", "--out-dir", "worker-dist/", "--out-name", "fl-worker-markdown", "target/wasm32-unknown-unknown/release/fl-worker-markdown.wasm"]
dependencies = ["build-dev-worker-markdown"]

[tasks.mv-dev-worker-highlight]
script = [
    "mv worker-dist/fl-worker-highlight_bg.wasm worker-dist/fl-worker-highlight_bg.original.wasm",
]
dependencies = ["bindgen-dev-worker-highlight"]

[tasks.mv-dev-worker-markdown]
script = [
    "mv worker-dist/fl-worker-markdown_bg.wasm worker-dist/fl-worker-markdown_bg.original.wasm",
]
dependencies = ["bindgen-dev-worker-markdown"]

# wasm-opt
[tasks.opt-dev-worker-highlight]
command = "wasm-opt"
args = ["-o", "worker-dist/fl-worker-highlight_bg.wasm", "worker-dist/fl-worker-highlight_bg.original.wasm"]
dependencies = ["mv-dev-worker-highlight"]

[tasks.opt-dev-worker-markdown]
command = "wasm-opt"
args = ["-o", "worker-dist/fl-worker-markdown_bg.wasm", "worker-dist/fl-worker-markdown_bg.original.wasm"]
dependencies = ["mv-dev-worker-markdown"]

[tasks.worker-highlight]
run_task = "opt-dev-worker-highlight"

[tasks.worker-markdown]
run_task = "opt-dev-worker-markdown"


[tasks.workers]
workspace = false
dependencies = ["worker-markdown", "worker-highlight"]
