[package]
name = "yew-router-macro"
version = "0.15.0"
authors = ["Hamza <muhammadhamza1311@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Contains macros used with yew-router"
repository = "https://github.com/yewstack/yew"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.32"
quote = "1.0.10"
syn = { version = "1.0.81", features = ["full","extra-traits"] }

[dev-dependencies]
rustversion = "1.0.5"
trybuild = "1.0.52"
yew-router = { path = "../yew-router" }
