[package]
name = "fl-www-common"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fl-www-macros = { path = "../fl-www-macros" }

wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"
js-sys = "0.3.55"
# web-sys
futures = "0.3.17"
gloo = { version = "0.3.0", features = ["futures"] }

console_log = { version = "0.2.0", features = ["color"] }
log = "0.4.14"

yew = { git = "https://github.com/yewstack/yew" }
stylist = { git = "https://github.com/futursolo/stylist-rs", version = "0.10.0", features = ["yew_integration", "yew_use_media_query", "yew_use_style"] }

thiserror = "1.0.29"
once_cell = "1.8.0"

syntect = { version = "4.6.0", default-features = false, features = ["parsing", "assets", "dump-load-rs", "regex-fancy"] }
bincode = "1.3.3"
serde = "1.0.130"

reqwest = "0.11"

[dependencies.web-sys]
version = "0.3.55"
features = [
  "Window",
  "MediaQueryList",
  "Storage",
  "CssStyleDeclaration",
  "Element",
  "HtmlElement",
  "ScrollIntoViewOptions",
  "ScrollBehavior",
  "ScrollToOptions",
]
