[package]
name = "fl-www-common"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fl-www-macros = { path = "../fl-www-macros" }
fl-www-core = { path = "../fl-www-core" }

wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"
js-sys = "0.3.55"
# web-sys
futures = "0.3.19"
gloo = { version = "0.6.0", features = ["futures"] }

log = "0.4.14"

yew = "0.19.3"
stylist = { version = "0.10.0", features = ["yew_integration"] }

serde = "1.0.133"
serde_json = "1.0.74"

thiserror = "1.0.30"
once_cell = "1.9.0"

[dependencies.web-sys]
version = "0.3.55"
features = [
  "Window",
  "Blob",
  "Navigator",
  "MediaQueryList",
  "Storage",
  "CssStyleDeclaration",
  "Element",
  "HtmlElement",
  "ScrollIntoViewOptions",
  "ScrollBehavior",
  "ScrollToOptions",
]
