[package]
name = "yew-query"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typed-builder = "0.9.1"
yew = "0.19.3"

wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"
js-sys = "0.3.55"
futures = "0.3.19"
async-trait = "0.1.52"

once_cell = "1.9.0"
thiserror = "1.0.30"
log = "0.4.14"
serde = { version = "1.0.132", features = ["rc"] }
serde_json = "1.0.73"
ahash = "0.7.6"

[dependencies.web-sys]
version = "0.3.55"
features = [
  "Window",
  "Headers",
  "Response",
  "Request",
  "RequestInit",
  "Url",
  "HtmlScriptElement",
  "Element",
  "HtmlElement",
  "Document",
  "HtmlHeadElement",
]
