[package]
name = "fl-www"
version = "0.1.0"
edition = "2018"

[dependencies]
fl-www-core = { path = "../fl-www-core" }
fl-www-common = { path = "../fl-www-common" }
fl-www-agents = { path = "../fl-www-agents" }

yew-query = { path = "../yew-query" }

wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"
js-sys = "0.3.55"
# web-sys
wee_alloc = "0.4.5"
futures = "0.3.17"
gloo = { version = "0.3.0", features = ["futures"] }
async-trait = "0.1.51"

console_log = { version = "0.2.0", features = ["color"] }
log = "0.4.14"

yew-feather = { git = "https://github.com/futursolo/yew-feather", branch = "compiled" }
yew-router = { path = "../yew-router" }
yew-side-effect = { git = "https://github.com/futursolo/yew-side-effect" }
yew = { git = "https://github.com/yewstack/yew" }
yew-agent = { git = "https://github.com/yewstack/yew", package = "yew-agent" }
stylist = { git = "https://github.com/futursolo/stylist-rs", version = "0.10.0", features = ["yew_integration"] }

i18n-embed = { version = "0.13.0", features = ["fluent-system", "web-sys-requester"] }
rust-embed = { version = "6.2.0", features = ["debug-embed"] }
i18n-embed-fl = "0.6.0"
unic-langid = "0.9.0"

chrono = { version = "0.4.19", features = ["wasmbind"] }
parking_lot = { version = "0.11.2", features = ["wasm-bindgen"] }

once_cell = "1.8.0"
serde = "1.0.130"

fastrand = "1.5.0"

[dependencies.web-sys]
version = "0.3.55"
features = [
  "Window",
  "MediaQueryList",
  "HtmlMetaElement",
  "HtmlLinkElement",
  "HtmlScriptElement",
  "Storage",
  "CssStyleDeclaration",
  "Element",
  "HtmlElement",
  "ScrollIntoViewOptions",
  "ScrollBehavior",
  "ScrollToOptions",
  "NodeList",
]
