[package]
name = "fl-www-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fl-www-core = { path = "../fl-www-core" }

async-trait = "0.1.51"
tokio = { version = "1.13.0", features = ["full"] }
futures = "0.3.17"

structopt = "0.3.25"
anyhow = "1.0.45"

chrono = { version = "0.4.19", features = ["wasmbind", "serde"] }
parking_lot = { version = "0.11.2", features = ["wasm-bindgen"] }

serde_json = "1.0.68"
serde = "1.0.130"

pulldown-cmark = { version = "0.8.0", default-features = false }
unicode-segmentation = "1.8.0"
atom_syndication = "0.11.0"
