[package]
name = "fl-www-macros"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.5.0"
itertools = "0.10.3"
once_cell = "1.9.0"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.36"
quote = "1.0.14"
rand = "0.8.4"
syn = { version = "1.0.84", features = ["full", "extra-traits"] }

#syntect = { version = "4.6.0", default-features = false, features = ["default-fancy"] }
#flate2 = { version = "1.0.22", default-features = false, features = ["rust_backend"] }
#bincode = "1.3.3"
#serde = "1.0.130"

# [target.'cfg(target_arch = "wasm32")'.dependencies]
# getrandom = { version = "0.2.3", features = ["js"] }

# [dependencies.web-sys]
# version = "0.3.55"
# features = [
#   "Window",
#   "MediaQueryList",
#   "Storage",
#   "CssStyleDeclaration",
#   "Element",
#   "HtmlElement",
#   "ScrollIntoViewOptions",
#   "ScrollBehavior",
#   "ScrollToOptions",
# ]
