---
name: Run Tests

on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          profile: minimal

      - name: Setup Rust wasm
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v1

      - name: Run cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Setup wasm-bindgen
        uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          version: 'latest'

      - name: Setup trunk
        uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'

      - name: Setup wasm-opt
        run: |
          WASM_OPT_VER=101

          cd /tmp

          curl -O -L https://github.com/WebAssembly/binaryen/releases/download/version_101/binaryen-version_$WASM_OPT_VER-x86_64-linux.tar.gz
          tar zxvf binaryen-version_$WASM_OPT_VER-x86_64-linux.tar.gz
          echo "PATH=$PATH:$(pwd)/binaryen-version_$WASM_OPT_VER/bin" >> $GITHUB_ENV

      - name: Build fl-worker-highlight
        run: |
          cargo build --target wasm32-unknown-unknown --bin fl-worker-highlight --release

          HASH=$(sha256sum target/wasm32-unknown-unknown/release/fl-worker-highlight.wasm)
          HASH=${HASH:0:12}
          FL_WORKER_HIGHLIGHT_NAME=fl-worker-highlight-$HASH

          wasm-bindgen --target no-modules --no-typescript --out-dir worker-dist/ --out-name $FL_WORKER_HIGHLIGHT_NAME target/wasm32-unknown-unknown/release/fl-worker-highlight.wasm

          cd worker-dist/
          mv $FL_WORKER_HIGHLIGHT_NAME"_bg.wasm" $FL_WORKER_HIGHLIGHT_NAME"_bg.original.wasm"
          wasm-opt -Oz -o $FL_WORKER_HIGHLIGHT_NAME"_bg.wasm" $FL_WORKER_HIGHLIGHT_NAME"_bg.original.wasm"
          rm $FL_WORKER_HIGHLIGHT_NAME"_bg.original.wasm"

          echo "FL_WORKER_HIGHLIGHT_PATH=$FL_WORKER_HIGHLIGHT_NAME.js" >> $GITHUB_ENV

      - name: Build fl-worker-markdown
        run: |
          cargo build --target wasm32-unknown-unknown --bin fl-worker-markdown --release

          HASH=$(sha256sum target/wasm32-unknown-unknown/release/fl-worker-markdown.wasm)
          HASH=${HASH:0:12}
          FL_WORKER_MARKDOWN_NAME=fl-worker-markdown-$HASH

          wasm-bindgen --target no-modules --no-typescript --out-dir worker-dist/ --out-name $FL_WORKER_MARKDOWN_NAME target/wasm32-unknown-unknown/release/fl-worker-markdown.wasm

          cd worker-dist/
          mv $FL_WORKER_MARKDOWN_NAME"_bg.wasm" $FL_WORKER_MARKDOWN_NAME"_bg.original.wasm"
          wasm-opt -Oz -o $FL_WORKER_MARKDOWN_NAME"_bg.wasm" $FL_WORKER_MARKDOWN_NAME"_bg.original.wasm"
          rm $FL_WORKER_MARKDOWN_NAME"_bg.original.wasm"

          echo "FL_WORKER_MARKDOWN_PATH=$FL_WORKER_MARKDOWN_NAME.js" >> $GITHUB_ENV

      - name: Build Website
        run: trunk --config Trunk.build.toml build --release index.release.html

      - name: Copy workers
        run: |
          cp worker-dist/* dist/

      - name: Build Metadata
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin fl-www-cli -- --in-dir . --out-dir meta-dist/
