---
name: Run Tests

on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          profile: minimal

      - name: Setup Rust wasm
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v1

      - name: Run cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Setup trunk
        uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'

      - name: Build Website
        run: trunk --config Trunk.build.toml build --release index.release.html

      - name: Build Metadata
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin landctl -- generate --in-dir . --out-dir dist/
